#!/bin/bash

#color codes
close="\e[0m"
green="\e[0;32m"
cyan="\e[0;36m"
lcyan="\e[1;36m"
lgreen="\e[1;32m"
lred="\e[1:31m"
red="\e[0;31m"
black="\e[0;30m"
darkgrey="\e[1;30m"
blue="\e[0;34m"
lblue="\e[1;34m"
purple="\e[0;35m"
lpurple="\e[1;35m"
brown="\e[0;33m"
yellow="\e[1;33m"
lgray="\e[0;37m"
white="\e[1;37m"
bold="\e[1m"
italic="\e[3m"
underline="\e[4m"
strikethrough="\e[9m"
blink="\e[5m"
reverse="\e[7m"
dim="\e[2m"
invisible="\e[8m"


sudo systemctl restart ssh

echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo -e "${red}${bold}${italic}  CHECKING DEPENDENCIES${close}"
echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo
ssh=$(dpkg -s openssh-server | grep "Status: install ok installed")
f1=0
if [ -n "$ssh" ]
then
echo -e "OPENSSH-SERVER   : ${brown}INSTALLED${close}"
f1=1
else
echo -e "OPENSSH-SERVER   : ${red}NOT INSTALLED${close} "
fi
if [ $f1 == 0 ]
then
echo -e "${lgreen}INSTALLING OPENSSH-SERVER${close}"
sudo apt install openssh-server
echo
echo
echo
fi
echo -ne "Enter the ip of server machine > "
read ip
echo -ne "Enter the first port > "
read a
echo -ne "Enter the second port > "
read b
echo -ne "Enter the third port > "
read c
echo -ne "Enter the username > "
read uname
telnet $ip $a
telnet $ip $b
telnet $ip $c
ssh $uname@$ip
sudo -sH

